=== mesosphere/marathon/src/main/resources/mesosphere/marathon/api/v2/AppDefinition.json
{
    "$schema": "http://json-schema.org/schema#",
    "additionalProperties": false,
    "properties": {
        "args": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "backoffFactor": {
            "minimum": 1.0,
            "type": "number"
        },
        "backoffSeconds": {
            "minimum": 0,
            "type": "integer"
        },
        "cmd": {
            "type": "string"
        },
        "constraints": {},
        "container": {
            "additionalProperties": false,
            "properties": {
                "docker": {
                    "additionalProperties": false,
                    "properties": {
                        "image": {
                            "type": "string"
                        },
                        "network": {
                            "type": "string"
                        },
                        "parameters": {
                            "items": {
                                "additionalProperties": false,
                                "properties": {
                                    "key": {
                                        "type": "string"
                                    },
                                    "value": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "key",
                                    "value"
                                ],
                                "type": "object"
                            },
                            "type": "array"
                        },
                        "portMappings": {
                            "items": {
                                "additionalProperties": false,
                                "properties": {
                                    "containerPort": {
                                        "maximum": 65535,
                                        "minimum": 0,
                                        "type": "integer"
                                    },
                                    "hostPort": {
                                        "maximum": 65535,
                                        "minimum": 0,
                                        "type": "integer"
                                    },
                                    "protocol": {
                                        "type": "string"
                                    },
                                    "servicePort": {
                                        "maximum": 65535,
                                        "minimum": 0,
                                        "type": "integer"
                                    }
                                },
                                "type": "object"
                            },
                            "type": "array"
                        },
                        "privileged": {
                            "type": "boolean"
                        }
                    },
                    "required": [
                        "image"
                    ],
                    "type": "object"
                },
                "type": {
                    "type": "string"
                },
                "volumes": {
                    "items": {
                        "additionalProperties": false,
                        "properties": {
                            "containerPath": {
                                "type": "string"
                            },
                            "hostPath": {
                                "type": "string"
                            },
                            "mode": {
                                "type": "string"
                            }
                        },
                        "type": "object"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "cpus": {
            "minimum": 0,
            "type": "number"
        },
        "dependencies": {
            "items": {
                "pattern": "^/?(([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])\\.)*([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])$",
                "type": "string"
            },
            "type": "array"
        },
        "disk": {
            "minimum": 0,
            "type": "number"
        },
        "env": {
            "patternProperties": {
                ".*": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "executor": {
            "type": "string"
        },
        "healthChecks": {
            "items": {
                "additionalProperties": false,
                "properties": {
                    "command": {
                        "type": "string"
                    },
                    "gracePeriodSeconds": {
                        "minimum": 0,
                        "type": "integer"
                    },
                    "intervalSeconds": {
                        "minimum": 0,
                        "type": "integer"
                    },
                    "maxConsecutiveFailures": {
                        "minimum": 0,
                        "type": "integer"
                    },
                    "path": {
                        "type": "string"
                    },
                    "portIndex": {
                        "minimum": 0,
                        "type": "integer"
                    },
                    "protocol": {
                        "type": "string"
                    },
                    "timeoutSeconds": {
                        "minimum": 0,
                        "type": "integer"
                    }
                },
                "type": "object"
            },
            "type": "array"
        },
        "id": {
            "pattern": "^/?(([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])\\.)*([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])$",
            "type": "string"
        },
        "instances": {
            "minimum": 0,
            "type": "integer"
        },
        "labels": {
            "additionalProperties": {
                "type": "string"
            },
            "type": "object"
        },
        "mem": {
            "minimum": 0,
            "type": "number"
        },
        "ports": {
            "items": {
                "maximum": 65535,
                "minimum": 0,
                "type": "integer"
            },
            "type": "array"
        },
        "requirePorts": {
            "type": "boolean"
        },
        "storeUrls": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "upgradeStrategy": {
            "additionalProperties": false,
            "properties": {
                "minimumHealthCapacity": {
                    "maximum": 1.0,
                    "minimum": 0.0,
                    "type": "number"
                }
            },
            "type": "object"
        },
        "uris": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "user": {
            "type": "string"
        }
    },
    "required": [
        "id"
    ],
    "type": "object"
}

=== mesosphere/marathon/tests/system/fixtures/universe.json
{
  "constraints": [
    [
      "hostname",
      "UNIQUE"
    ]
  ],
  "healthChecks": [
    {
      "timeoutSeconds": 5,
      "protocol": "HTTP",
      "portIndex": 0,
      "path": "/repo-empty-v3.json",
      "maxConsecutiveFailures": 3,
      "intervalSeconds": 30,
      "gracePeriodSeconds": 120
    }
  ],
  "container": {
    "volumes": [],
    "docker": {
      "portMappings": [
        {
          "protocol": "tcp",
          "hostPort": 8085,
          "containerPort": 80
        }
      ],
      "image": "mesosphere/universe-server:marathon-f0080a1a83256449",
      "network": "BRIDGE"
    },
    "type": "DOCKER"
  },
  "requirePorts": true,
  "mem": 128,
  "cpus": 0.25,
  "instances": 1,
  "id": "/universe"
}
